- name: Apache HTTP → HTTPS リダイレクト設定
  blockinfile:
    path: /etc/httpd/conf.d/http-redirect.conf
    create: yes
    block: |
      <VirtualHost *:80>
          ServerName mytest-portfolio.xyz
          Redirect permanent / https://mytest-portfolio.xyz/
      </VirtualHost>

- name: Apache 再起動（HTTPSリダイレクト設定後）
  systemd:
    name: httpd
    state: restarted
