# site.yml
- hosts: all
  become: true
  tasks:
    - import_tasks: tasks/setup_apache.yml
    - import_tasks: tasks/setup_certbot.yml
    - import_tasks: tasks/setup_fail2ban.yml
    - import_tasks: tasks/setup_htpasswd.yml
    - import_tasks: tasks/setup_https_redirect.yml
    - import_tasks: tasks/setup_goaccess.yml
    - import_tasks: tasks/setup_sshd_config.yml
