# ansible_ec2_setup/site.yml
- hosts: all
  become: true
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    domain_name: "mytest-portfolio.xyz"

  tasks:
    - import_tasks: tasks/setup_apache.yml
    - import_tasks: tasks/setup_certbot.yml
    - import_tasks: tasks/setup_fail2ban.yml
    - import_tasks: tasks/setup_htpasswd.yml
    - import_tasks: tasks/setup_https_redirect.yml
    - import_tasks: tasks/setup_goaccess.yml
    - import_tasks: tasks/setup_sshd_config.yml

