name: Deploy to EC2 via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Ansible playbook on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.249.191.181 << 'EOF'
            cd ~/ec2-https-webserver/ansible_ec2_setup
            git pull
            ansible-playbook site.yml
          EOF
# Trigger test
